"""add in_list to game status

Revision ID: 0f08bdd67a07
Revises: 78edbe61a648
Create Date: 2025-03-19 15:33:55.953896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f08bdd67a07'
down_revision: Union[str, None] = '78edbe61a648'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_games', 'status',
                    type_=sa.Enum('WANT_TO_PLAY', 'PLAYING', 'PLAYED', 'IN_LIST', name='gamestatus'),
                    existing_type=sa.Enum('WANT_TO_PLAY', 'PLAYING', 'PLAYED', name='gamestatus'),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_games', 'status',
                    type_=sa.Enum('WANT_TO_PLAY', 'PLAYING', 'PLAYED', name='gamestatus'),
                    existing_type=sa.Enum('WANT_TO_PLAY', 'PLAYING', 'PLAYED', 'IN_LIST', name='gamestatus'),
                    existing_nullable=False)
    # ### end Alembic commands ###
