"""add_is_deleted_column_to_games

Revision ID: 106f4b165054
Revises: 2854968ac07b
Create Date: 2025-03-14 15:49:27.491804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '106f4b165054'
down_revision: Union[str, None] = '2854968ac07b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'is_deleted')
    # ### end Alembic commands ###
