"""add hypes field to games table

Revision ID: 8fd8b85123ee
Revises: dc4e7c9f3395
Create Date: 2025-02-14 21:31:08.434423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fd8b85123ee'
down_revision: Union[str, None] = 'dc4e7c9f3395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('hypes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'hypes')
    # ### end Alembic commands ###
