"""Add detailed game info fields

Revision ID: a29d1af0ae2c
Revises: 0e902e3c206a
Create Date: 2025-03-09 06:45:33.782243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a29d1af0ae2c'
down_revision: Union[str, None] = '0e902e3c206a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('publishers', sa.String(), nullable=True))
    op.add_column('games', sa.Column('age_ratings', sa.JSON(), nullable=True, comment='Age ratings (PEGI, ESRB)'))
    op.add_column('games', sa.Column('game_engines', sa.JSON(), nullable=True, comment='Game engines used'))
    op.add_column('games', sa.Column('multiplayer_modes', sa.JSON(), nullable=True, comment='Multiplayer features'))
    op.add_column('games', sa.Column('language_supports', sa.JSON(), nullable=True, comment='Supported languages'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'language_supports')
    op.drop_column('games', 'multiplayer_modes')
    op.drop_column('games', 'game_engines')
    op.drop_column('games', 'age_ratings')
    op.drop_column('games', 'publishers')
    # ### end Alembic commands ###
