"""Create games table

Revision ID: dc4e7c9f3395
Revises: 
Create Date: 2025-02-14 20:19:17.019174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc4e7c9f3395'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('igdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('storyline', sa.String(), nullable=True),
    sa.Column('cover_image', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('aggregated_rating', sa.Float(), nullable=True),
    sa.Column('total_rating', sa.Float(), nullable=True),
    sa.Column('total_rating_count', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(), nullable=True),
    sa.Column('platforms', sa.String(), nullable=True),
    sa.Column('first_release_date', sa.DateTime(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('videos', sa.JSON(), nullable=True),
    sa.Column('similar_games', sa.JSON(), nullable=True),
    sa.Column('developers', sa.String(), nullable=True),
    sa.Column('game_modes', sa.String(), nullable=True),
    sa.Column('player_perspectives', sa.String(), nullable=True),
    sa.Column('themes', sa.String(), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_igdb_id'), 'games', ['igdb_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_games_igdb_id'), table_name='games')
    op.drop_table('games')
    # ### end Alembic commands ###
