"""initial

Revision ID: ffbdcf4a7fd9
Revises: b9c7709bb53d
Create Date: 2025-02-17 13:16:46.852250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbdcf4a7fd9'
down_revision: Union[str, None] = 'b9c7709bb53d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('popularity_value', sa.Float(), nullable=True, comment="Steam's 24hr peak players value"))
    op.drop_column('games', 'time_to_beat_normally')
    op.drop_column('games', 'time_to_beat_hastily')
    op.drop_column('games', 'time_to_beat_completely')
    op.drop_column('games', 'time_to_beat_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('time_to_beat_count', sa.INTEGER(), autoincrement=False, nullable=True, comment='Total number of time to beat submissions for this game'))
    op.add_column('games', sa.Column('time_to_beat_completely', sa.INTEGER(), autoincrement=False, nullable=True, comment='Average time (in seconds) to finish the game to 100% completion'))
    op.add_column('games', sa.Column('time_to_beat_hastily', sa.INTEGER(), autoincrement=False, nullable=True, comment='Average time (in seconds) to finish the game to its credits without extras'))
    op.add_column('games', sa.Column('time_to_beat_normally', sa.INTEGER(), autoincrement=False, nullable=True, comment='Average time (in seconds) to finish the game while mixing in some extras'))
    op.drop_column('games', 'popularity_value')
    # ### end Alembic commands ###
