"""Initial migration

Revision ID: 457428200ad9
Revises: 
Create Date: 2025-02-15 21:42:33.239059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '457428200ad9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('igdb_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('storyline', sa.Text(), nullable=True),
    sa.Column('first_release_date', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('aggregated_rating', sa.Float(), nullable=True),
    sa.Column('total_rating', sa.Float(), nullable=True),
    sa.Column('total_rating_count', sa.Integer(), nullable=True),
    sa.Column('hypes', sa.Integer(), nullable=True),
    sa.Column('cover', sa.JSON(), nullable=True),
    sa.Column('screenshots', sa.JSON(), nullable=True),
    sa.Column('videos', sa.JSON(), nullable=True),
    sa.Column('genres', sa.JSON(), nullable=True),
    sa.Column('platforms', sa.JSON(), nullable=True),
    sa.Column('themes', sa.JSON(), nullable=True),
    sa.Column('similar_games', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('involved_companies', sa.JSON(), nullable=True),
    sa.Column('game_modes', sa.JSON(), nullable=True),
    sa.Column('player_perspectives', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('igdb_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    # ### end Alembic commands ###
