"""add synced_games table

Revision ID: 16a4d29357cc
Revises: 2c587d671d4d
Create Date: 2025-12-13 16:13:20.542362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '16a4d29357cc'
down_revision: Union[str, None] = '2c587d671d4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psn_igdb_mappings_igdb_id'), table_name='psn_igdb_mappings')
    op.drop_index(op.f('ix_psn_igdb_mappings_trophy_id'), table_name='psn_igdb_mappings')
    op.drop_table('psn_igdb_mappings')
    op.drop_index(op.f('ix_psn_title_lookup_concept_id'), table_name='psn_title_lookup')
    op.drop_index(op.f('ix_psn_title_lookup_title_id'), table_name='psn_title_lookup')
    op.drop_index(op.f('ix_psn_title_lookup_title_id_concept'), table_name='psn_title_lookup')
    op.drop_table('psn_title_lookup')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psn_title_lookup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('psn_title_lookup_pkey'))
    )
    op.create_index(op.f('ix_psn_title_lookup_title_id_concept'), 'psn_title_lookup', ['title_id', 'concept_id'], unique=False)
    op.create_index(op.f('ix_psn_title_lookup_title_id'), 'psn_title_lookup', ['title_id'], unique=True)
    op.create_index(op.f('ix_psn_title_lookup_concept_id'), 'psn_title_lookup', ['concept_id'], unique=False)
    op.create_table('psn_igdb_mappings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('trophy_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('igdb_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('psn_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('use_count', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('psn_igdb_mappings_pkey'))
    )
    op.create_index(op.f('ix_psn_igdb_mappings_trophy_id'), 'psn_igdb_mappings', ['trophy_id'], unique=True)
    op.create_index(op.f('ix_psn_igdb_mappings_igdb_id'), 'psn_igdb_mappings', ['igdb_id'], unique=False)
    # ### end Alembic commands ###
