"""test_connection

Revision ID: 30792afd1955
Revises: ffbdcf4a7fd9
Create Date: 2025-02-17 13:46:05.664521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30792afd1955'
down_revision: Union[str, None] = 'ffbdcf4a7fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'popularity_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('popularity_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True, comment="Steam's 24hr peak players value"))
    # ### end Alembic commands ###
