"""test_connection_2

Revision ID: 37b6922f1ed4
Revises: 7829dcd5d20a
Create Date: 2025-02-19 13:24:10.052655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37b6922f1ed4'
down_revision: Union[str, None] = '7829dcd5d20a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_library')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_library',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('added_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='user_library_game_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_library_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'game_id', name='user_library_pkey')
    )
    # ### end Alembic commands ###
