"""add_igdb_cover_url_to_synced_games

Revision ID: 509348ff0ce3
Revises: 16a4d29357cc
Create Date: 2025-12-14 01:15:34.683392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '509348ff0ce3'
down_revision: Union[str, None] = '16a4d29357cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_psn_title_lookup_concept_id'), table_name='psn_title_lookup')
    op.drop_index(op.f('ix_psn_title_lookup_title_id'), table_name='psn_title_lookup')
    op.drop_index(op.f('ix_psn_title_lookup_title_id_concept'), table_name='psn_title_lookup')
    op.drop_table('psn_title_lookup')
    op.drop_index(op.f('ix_synced_games_status'), table_name='synced_games')
    op.drop_index(op.f('ix_synced_games_user_platform'), table_name='synced_games')
    op.drop_index(op.f('ix_synced_games_user_platform_id'), table_name='synced_games')
    op.drop_table('synced_games')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('synced_games',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('igdb_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('igdb_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('match_confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('match_method', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_list', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('playtime_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_synced_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('synced_games_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('synced_games_pkey'))
    )
    op.create_index(op.f('ix_synced_games_user_platform_id'), 'synced_games', ['user_id', 'platform', 'platform_id'], unique=True)
    op.create_index(op.f('ix_synced_games_user_platform'), 'synced_games', ['user_id', 'platform'], unique=False)
    op.create_index(op.f('ix_synced_games_status'), 'synced_games', ['user_id', 'status'], unique=False)
    op.create_table('psn_title_lookup',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('concept_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('psn_title_lookup_pkey'))
    )
    op.create_index(op.f('ix_psn_title_lookup_title_id_concept'), 'psn_title_lookup', ['title_id', 'concept_id'], unique=False)
    op.create_index(op.f('ix_psn_title_lookup_title_id'), 'psn_title_lookup', ['title_id'], unique=True)
    op.create_index(op.f('ix_psn_title_lookup_concept_id'), 'psn_title_lookup', ['concept_id'], unique=False)
    # ### end Alembic commands ###
