"""add user model

Revision ID: 7829dcd5d20a
Revises: ffbdcf4a7fd9
Create Date: 2025-02-18 18:24:18.667409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7829dcd5d20a'
down_revision: Union[str, None] = 'ffbdcf4a7fd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('games', 'similar_games',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='List of similar games with details (id, name, cover_image, rating, genres)',
               existing_comment='List of similar games with full details (id, name, cover_image, rating, genres)',
               existing_nullable=True)
    op.drop_index('ix_games_developer_id', table_name='games')
    op.drop_column('games', 'developer_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('developer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('ix_games_developer_id', 'games', ['developer_id'], unique=False)
    op.alter_column('games', 'similar_games',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               comment='List of similar games with full details (id, name, cover_image, rating, genres)',
               existing_comment='List of similar games with details (id, name, cover_image, rating, genres)',
               existing_nullable=True)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
