"""Add aggregated_rating_count

Revision ID: b7b9f81b57ff
Revises: 106f4b165054
Create Date: 2025-03-14 18:20:15.655089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7b9f81b57ff'
down_revision: Union[str, None] = '106f4b165054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('aggregated_rating_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'aggregated_rating_count')
    # ### end Alembic commands ###
