"""Add version_parent and version_title fields

Revision ID: e13d62ca857f
Revises: a92c964c8f71
Create Date: 2025-03-18 12:34:37.902682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e13d62ca857f'
down_revision: Union[str, None] = 'a92c964c8f71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('version_parent', sa.JSON(), nullable=True, comment='Parent game if this is a specific edition'))
    op.add_column('games', sa.Column('version_title', sa.String(), nullable=True, comment="Title of this edition (e.g., 'Gold Edition')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'version_title')
    op.drop_column('games', 'version_parent')
    # ### end Alembic commands ###
