"""Add ports and standalone_expansions fields

Revision ID: e6b95e875e4a
Revises: c727f8773483
Create Date: 2025-03-18 11:42:16.153488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e6b95e875e4a'
down_revision: Union[str, None] = 'c727f8773483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('ports', sa.JSON(), nullable=True, comment='List of ports of this game'))
    op.add_column('games', sa.Column('standalone_expansions', sa.JSON(), nullable=True, comment='List of standalone expansions of this game'))
    op.drop_column('games', 'seasons')
    op.drop_column('games', 'packs')
    op.drop_column('games', 'episodes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('episodes', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('packs', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('games', sa.Column('seasons', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('games', 'standalone_expansions')
    op.drop_column('games', 'ports')
    # ### end Alembic commands ###
